defaults:
  - default
  - _self_

# Override from `default` config
id: TSP-v0
sync_env: True
num_envs: 16

# Wrapper to be instantiated
wrapper:
  _target_: gymnasium.make
  id: ${env.id}
  render_mode: rgb_array
  n_nodes: 10